- name: File Level Variables
  hosts: local
  connection: local
  vars_files:
    -movies.yaml
  tasks:
  - name: Display movie information
    ansible.builtin.debug:
      msg: "The movie {{ movie }} is releasing on {{ release_date }}"