- name: Conditions in Ansible
  hosts: web
  vars:
    movie: Peddi
    release_date: 4 June 2026
  tasks:
  - name: Check if the movie is releasing in June
    ansible.builtin.debug:
      msg: "The movie {{ movie }} is releasing in June."
    when: release_date.endswith('June')